name: Flutter Split APK Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Upgrade Flutter dependencies
        run: flutter pub upgrade

      - name: Commit updated dependencies
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pub dependencies [skip ci]"
          add_options: '-f'
          file_pattern: "pubspec.lock"

      - name: Setup environment file
        run: |
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env
          echo "API_KEY_WEATHERAPI=${{ secrets.API_KEY_WEATHERAPI }}" >> .env
          echo "API_KEY_OPENROUTER=${{ secrets.API_KEY_OPENROUTER }}" >> .env

      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          VERSION_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          mkdir release_apks 
          
          if [ -f build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ]; then
            cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk release_apks/WeatherMaster.${VERSION_NAME}.arm64-v8a.apk
          fi
          
          if [ -f build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk ]; then
            cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk release_apks/WeatherMaster.${VERSION_NAME}.armeabi-v7a.apk
          fi
          
          if [ -f build/app/outputs/flutter-apk/app-x86_64-release.apk ]; then
            cp build/app/outputs/flutter-apk/app-x86_64-release.apk release_apks/WeatherMaster.${VERSION_NAME}.x86_64.apk
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: release_apks/
