name: SonarCloud
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Create .env file
        run: |
          cat <<EOF > .env
          API_TOKEN=${{ secrets.API_TOKEN }}
          API_KEY_WEATHERAPI=${{ secrets.API_KEY_WEATHERAPI }}
          API_KEY_OPENROUTER=${{ secrets.API_KEY_OPENROUTER }}
          EOF

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          
      - name: Build
        run: flutter build apk --release --split-per-abi
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
